# Generated by Django 5.0 on 2024-06-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_portfolio_academic_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
